# Generated by Django 3.2.15 on 2022-09-28 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bikeimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeimages',
            name='image',
            field=models.ImageField(null=True, upload_to='bike-images', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
