# Generated by Django 3.2.15 on 2022-09-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bikeimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeimages',
            name='image',
            field=models.ImageField(null=True, upload_to='bike-images'),
        ),
    ]
