# Generated by Django 3.2.15 on 2022-10-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bikeimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='bike',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.bikes'),
        ),
    ]
