# Generated by Django 3.2.15 on 2022-10-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
