# Generated by Django 3.2.15 on 2022-10-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sales_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sale_price',
            field=models.PositiveIntegerField(),
        ),
    ]
